---
- name: 'Provision Image'
  hosts: default
  become: true

  tasks:
    - name: Install qemu-guest-agent with apt
      ansible.builtin.apt:
        name: 'qemu-guest-agent'
        update_cache: yes